language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: alex@alexnorton.com
  skip_cleanup: true
  api_key:
    secure: qjHc9merS0N4h7B5Q1m4oAQi2xsfxhyGyf6CVqPAluEvoxX4XrIUG12VjU19uqrDNOI/dC4FrLlSGr3KtvLQUH16G7DBFsA1fvbDeTfBs0zobT6+DX+75rcAHJkOos/5EwleVL0zHqwpKZcWkb6rJKJ/FOAllS21DFNNLt/6HdKH0EMTtCIOAhBDFZchM1qCWMNjed7ZC6oFqVfKQAxUxMp7eWEt9fi7YnXy6KZpq4oI5O/8qc2NGKweC7r1w0uXbv0anXP/1hjYSa6tIEzaec1NWW26OqQHJx8ErqVdAONzKt7w9yqB3H8yyWdH/3E/JXgUzrc+1E7ksGylCVN9PowolnxyTtILGF6GmYN3zRv3VnTVglWLGwU6yCF9w0gJvPjD0YHZPzNGZybfUbfg9kQvpU1/O/2GFCOU+PQZFVLtiXgy+ycoHuFZbQZcWo+bRZxMKr44Ct4+5423jPdtVG/49MaiVe4ACZ3goNykzhf2RcB4hrP700KxRcz/DBzv+YQXfIb/qEF6oJ7suA2p2MLVviP8bbnUr3qSdGIOqGyfnY3gMKovayOxe5EEoDVORN/e5EtKuw/JNyS2XVt4GHrKHY1oKQ19FXbLfEm0ovD09zNjt2l/7Wcw18eRoIoNhjHlcQb9UYqRZAqR3sPnTZ/nSFjSAAdMbibeX+xHaIM=
  on:
    tags: true
    repo: bbc/transcript-editor
